### PR TITLE
Homepage screening

### PR DESCRIPTION
**Pull request by EmilioSanchezLernia**
Added screening times to the home page, including the room it is showing in and the name of the movie that is shown.
Also included a test with mock data to make sure the logic is working properly.

### CODE REVIEW

**Review by MatsJoh50 — DISMISSED** [review]
Posted in the wrong PR

**Review by AlexanderK88 — CHANGES_REQUESTED** [review]
I noticed that the convertToEuropeanTime and convertToEuropeanDate functions are converting the ISO time from the API response to a local time and date without specifying a timezone.

Since the API returns dates and times in UTC, and the date and time are being displayed to the user in their local time zone, this could lead to confusion or incorrect data being displayed. For example, a screening that starts at 10:00 UTC would be displayed as starting at 17:00 in Thailand, which could be several hours off if the user is in a different time zone.

To fix this, I suggest specifying the timezone in the toLocaleString method. This will ensure that the date and time not converted to the user's local time. Here's how you can do it:

image

While it's true that most users visiting the site will have the same local time as the API, it's important to consider other scenarios as well. For instance, if you are running any tests that are checking the rendered data on the frontend, they will fail if you are comparing screening times to the API or mocked data and the tester is in a different timezone. This change will ensure that the date and time are displayed correctly in all time zones and testing scenarios.

This is a screenshot with how the page looks for me:
Screenshot 2024-02-04 204344

This is a screenshot of how it looks if you add the timezone:
Screenshot 2024-02-04 204414

**Comment by EmilioSanchezLernia** [comment]
> I noticed that the convertToEuropeanTime and convertToEuropeanDate functions are converting the ISO time from the API response to a local time and date without specifying a timezone.

Thanks for notifying me.
I didn't know it had to be specified like that since it worked on my computer and I didn't think about people outside of Sweden using it. 
I've hopefully fixed it as per your suggestion!

**Review by AlexanderK88 — APPROVED** [review]
The changes that i have requested has been made and the code works correctly when i try it.

**Review by Weeezzt — APPROVED** [review]
I think it looks good, one thing that you might want to add is error handling for the fetchScreenings function. You could add a try/catch but otherwise i think its a ok.

**Comment by EmilioSanchezLernia** [comment]
> I think it looks good, one thing that you might want to add is error handling for the fetchScreenings function. You could add a try/catch but otherwise i think its a ok.

I forgot about adding try and catch, added it now. 
Hope everything is okay!

**Pull request merged**
